### ISSUE TITLE
Design Test PCB in Altium

### ISSUE THREAD

**Issue by TrevorBuchanan** [WSUCptSCapstone-S24-F24/-mda-unity3dapp-#52] opened 2024-08-29 18:32 UTC
Create a test PCB in Altium to use in the simulation.

**Comment by ErisTheBeholder** [comment] 2024-11-01 03:30
New version of the problem is being handled by Trevor, I am closing this to prevent confusion.

**Closed by ErisTheBeholder** 2024-11-01 03:30 UTC
